fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_front:
    resource: "@AppFrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
